apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Database connection URL para ambiente PRODUCTION
  database-url: "jdbc:postgresql://postgres-service:5432/bridal_cover_crm_prod"
  
  # Application log level
  app-log-level: "INFO"
  
  # SQL log level
  sql-log-level: "ERROR"
  
  # Timezone
  timezone: "America/Sao_Paulo"

