apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: bridal-cover-crm-base

resources:
  - secret.yaml
  - configmap.yaml
  - postgres-statefulset.yaml
  - pgadmin.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  project: bridal-cover-crm
  managed-by: kustomize

