apiVersion: v1
kind: Service
metadata:
  name: bridal-cover-crm
  labels:
    app: bridal-cover-crm
spec:
  selector:
    app: bridal-cover-crm
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8080
      nodePort: 30089
